Rostislav / 85421 / Migrate cashier constants to TS
rostislav-deriv/deriv-app pull request #3
Opened 2023-03-02 14:14 UTC by rostislav-deriv

## Changes:

Please include a summary of the change and which issue is fixed below:
-   ...

## When you need to add unit test

-   [ ] If this change disrupt current flow
-   [ ] If this change is adding new flow

## When you need to add integration test

-   [ ] If components from external libraries are being used to define the flow, e.g. @deriv/components
-   [ ] If it relies on a very specific set of props with no default behavior for the current component.

## Test coverage checklist (for reviewer)

-   [ ] Ensure utility / function has a test case 
-   [ ] Ensure all the tests are passing

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [x] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2023-03-09 14:03 UTC, rostislav-deriv commented on packages/cashier/src/constants/transaction-status.tsx
> +    if (
These are type-guards allowing to index `status_list` in two of of the two possible cases (`deposit` and `withdrawal`)

2023-03-09 14:04 UTC, rostislav-deriv commented on packages/cashier/src/constants/transaction-status.tsx
> +    return undefined;
Not sure what to have returned here, but smth should be, I suppose

2023-03-09 14:10 UTC, rostislav-deriv commented on packages/cashier/src/constants/transaction-status.tsx
> +    } else if (
These are type-guards allowing to index `status_list` in two of of the two possible cases (`deposit` and `withdrawal`)

2023-03-13 09:36 UTC, rostislav-deriv commented on packages/cashier/src/stores/transaction-history-store.ts
> +                    // @ts-ignore
I can explain

2023-03-13 09:44 UTC, rostislav-deriv commented on packages/cashier/src/stores/transaction-history-store.ts
> +                    // @ts-ignore
This is the point where we might get `CAPITALIZED_STATUS_CODE` from the API. The property type is not string but `'status_one' | 'status_two' | 'status_three' | ...` union type (I guess). These statuses are supposed to be lowercase, but the API doesn't know it. So whatever we get from the API, we treat it as a `string` instead of the union type to make it lowercase (hence the `@ts-ignore`), and then we are sure the resulting string is one of the union type options.

2023-03-13 13:08 UTC, rostislav-deriv commented on packages/cashier/src/components/recent-transaction/recent-transaction.tsx
> +                                    {status!.name}
Because the fallback return value is `undefined`

2023-03-13 13:10 UTC, rostislav-deriv commented on packages/cashier/src/constants/transaction-status.tsx
> -    const formatted_status_code = status_code.toLowerCase();
It is ensured in transaction history store now

2023-03-13 13:12 UTC, rostislav-deriv commented on packages/cashier/src/constants/transaction-status.tsx
> +        | 'pending'
Maybe a better way to type parameters here exists, this is the one I've come up with

2023-03-13 13:20 UTC, rostislav-deriv commented on packages/components/src/components/static-url/static-url.jsx
> -    const { is_appstore } = React.useContext(PlatformContext);
This was not really used, and after migrating the file to TS it caused build problems, so I removed it

2023-03-14 04:48 UTC, hamid-deriv commented on packages/cashier/src/components/recent-transaction/recent-transaction.tsx
> +                                    {status!.name}
Can't we change this part to something like this? also for line 100 (`{status!.transaction_hash}`)
```
{status && (
    <Text as='p' size='xxxs'>
        {status.name}
    </Text>
)}
```
Also, I think you will get a warning for using the `!` inside the code, so it's better not to use it.

2023-03-14 04:48 UTC, hamid-deriv commented on packages/cashier/src/components/recent-transaction/recent-transaction.tsx
> +    const submit_date_moment = epochToMoment(submit_date).format('MMM D, YYYY');
What is the reason for this? @rostislav-deriv

2023-03-14 04:48 UTC, hamid-deriv commented on packages/cashier/src/components/recent-transaction/recent-transaction.tsx
> +    const transaction_type_display_text = transaction_type[0].toUpperCase() + transaction_type.slice(1);
@rostislav-deriv Also this one

2023-03-14 04:48 UTC, hamid-deriv commented on packages/cashier/src/components/recent-transaction/recent-transaction.tsx
> +                                    {status!.name}
Also, For line 65.

2023-03-14 04:48 UTC, hamid-deriv commented on packages/cashier/src/constants/transaction-status.tsx
> +    return undefined;
@rostislav-deriv Maybe you can use a variable for storing returned status and return that at the end. Also, it is useful to avoid handling `undefined` in the `recent-transactions` file.

2023-03-14 04:48 UTC, hamid-deriv commented on packages/cashier/src/types/crypto-transaction-details.types.ts
> +    status_code:
As we use this type in different places, I think it's better to create an exported `status_code` type and use it everywhere. @rostislav-deriv

2023-03-14 04:48 UTC, hamid-deriv commented on packages/cashier/src/types/crypto-transaction-details.types.ts
> +    transaction_type: 'deposit' | 'withdrawal';
Also for this.

2023-03-14 04:48 UTC, hamid-deriv commented on packages/cashier/src/stores/transaction-history-store.ts
> +                    // @ts-ignore
For this, you can export the status_code type and then use it here:
```
status_code: el.status_code.toLowerCase() as TStatusCode,
```

2023-03-14 05:27 UTC, farzin-deriv reviewed
@rostislav-deriv Please use `as const` for all the objects in `packages/cashier/src/constants/constants.ts` 🙏🏻

2023-03-14 05:27 UTC, farzin-deriv commented on packages/cashier/src/types/crypto-transaction-details.types.ts
> +    status_code:
@rostislav-deriv Aren't they coming from `@deriv/api`? 🤔 Maybe we have a type for them in `@deriv/api-types`? 🤔

2023-03-14 05:27 UTC, farzin-deriv commented on packages/cashier/src/stores/transaction-history-store.ts
> +                    // @ts-ignore
@rostislav-deriv I have a question, If the API response is all in CAP, Then why in code do we change and manipulate the   `status_code` to be lowercase on our side? Why we are not just using the same data we get from API? 🤔 

cc: @hamid-deriv

2023-03-14 09:36 UTC, rostislav-deriv commented on packages/cashier/src/constants/transaction-status.tsx
> +    return undefined;
Done

2023-03-14 09:40 UTC, rostislav-deriv commented on packages/cashier/src/stores/transaction-history-store.ts
> +                    // @ts-ignore
Replaced `@ts-ignore` with a cast.
@farzin-deriv we don't know what is the convention on the back end, so I went with a lower-risk approach and refactored without changing this `.toLowercase()` logic

2023-03-14 09:41 UTC, rostislav-deriv commented on packages/cashier/src/stores/transaction-history-store.ts
> +                    // @ts-ignore
If the casing changes later on the API side, we won't have to change anything, that's a plus

2023-03-14 09:42 UTC, rostislav-deriv commented on packages/cashier/src/components/recent-transaction/recent-transaction.tsx
> +                                    {status!.name}
Removed `!`

2023-03-14 09:43 UTC, farzin-deriv commented on packages/cashier/src/stores/transaction-history-store.ts
> +                    // @ts-ignore
@rostislav-deriv We know what is backend convention, You can check it [here](https://github.com/regentmarkets/binary-websocket-api/blob/master/config/v3/cashier_payments/receive.json#L56).

<img width="948" alt="image" src="https://user-images.githubusercontent.com/72082844/224960780-d4ec5db8-bd7d-49ec-99b8-16ceba92b778.png">

2023-03-14 09:45 UTC, rostislav-deriv commented on packages/cashier/src/components/recent-transaction/recent-transaction.tsx
> +    const submit_date_moment = epochToMoment(submit_date).format('MMM D, YYYY');
Not overriding imported stuff with values to display, thought this would be better

2023-03-14 09:47 UTC, rostislav-deriv commented on packages/cashier/src/types/crypto-transaction-details.types.ts
> +    status_code:
Created the types and exporting them now from the type file

2023-03-14 10:11 UTC, rostislav-deriv commented on packages/cashier/src/stores/transaction-history-store.ts
> +                    // @ts-ignore
The link is 404 for me unfortunately

2023-03-14 10:11 UTC, rostislav-deriv commented on packages/cashier/src/stores/transaction-history-store.ts
> +                    // @ts-ignore
@farzin-deriv

2023-03-14 10:11 UTC, rostislav-deriv commented on packages/cashier/src/stores/transaction-history-store.ts
> +                    // @ts-ignore
But I see the convention now

2023-03-14 10:12 UTC, rostislav-deriv commented on packages/cashier/src/stores/transaction-history-store.ts
> +                    // @ts-ignore
Gonna align the front end code to CAP then, thx

2023-03-14 10:20 UTC, rostislav-deriv commented on packages/cashier/src/stores/transaction-history-store.ts
> +                    // @ts-ignore
No info in the client code tho, if I get it right (searching for one of the statuses, case-insensitive, in project folder; expected to see smth in `node_modules` as a type of a dependency's documentation/code)

<img width="963" alt="Screenshot 2023-03-14 at 13 13 25" src="https://user-images.githubusercontent.com/119863957/224970023-d02a0042-f028-4403-af1c-ede25cf33d7e.png">

2023-03-14 10:24 UTC, rostislav-deriv commented on packages/cashier/src/types/crypto-transaction-details.types.ts
> +    status_code:
@farzin-deriv, answering your question, in the source code (and `node_modules`) there're no mention of one of the status codes used, outside of `transaction-status.js(.ts)`

<img width="963" alt="Screenshot 2023-03-14 at 13 13 25" src="https://user-images.githubusercontent.com/119863957/224970567-29065bd6-de72-4242-bc07-00e5a18135a8.png">

2023-03-14 10:29 UTC, rostislav-deriv commented on packages/cashier/src/components/recent-transaction/recent-transaction.tsx
> +    const transaction_type_display_text = transaction_type[0].toUpperCase() + transaction_type.slice(1);
Same reason, to separate what we import and what we display

2023-03-14 11:54 UTC, rostislav-deriv commented on packages/cashier/src/components/recent-transaction/recent-transaction.tsx
> +    const submit_date_moment = epochToMoment(submit_date).format('MMM D, YYYY');
There also were TS issues with this code @hamid-deriv

2023-03-14 12:00 UTC, rostislav-deriv commented on packages/cashier/src/components/recent-transaction/recent-transaction.tsx
> +    const submit_date_moment = epochToMoment(submit_date).format('MMM D, YYYY');
Namely,

![Screenshot 2023-03-14 at 14 59 51](https://user-images.githubusercontent.com/119863957/224994526-37622371-39d5-46c0-88b0-03834052fd59.png)

2023-03-14 12:01 UTC, rostislav-deriv commented on packages/cashier/src/components/recent-transaction/recent-transaction.tsx
> +    const transaction_type_display_text = transaction_type[0].toUpperCase() + transaction_type.slice(1);
And to avoid TS issues

2023-03-14 12:09 UTC, rostislav-deriv commented
Made suggested changes guys @hamid-deriv @farzin-deriv

2023-03-15 04:15 UTC, farzin-deriv requested changes

2023-03-15 04:15 UTC, farzin-deriv commented on packages/cashier/src/constants/transaction-status.tsx
> +    } else if (
@rostislav-deriv This is not what a type guard function is, You can define two type guard function as below and then use them.

```ts
const isDeposit = (key: TStatusCode): key is keyof typeof data.deposit => typeof key === typeof data.deposit;
const isWithdrawal = (key: TStatusCode): key is keyof typeof data.withdrawal => typeof key === typeof data.withdrawal;

if (transaction_type === 'deposit' && isDeposit(status_code)) {
    return data[transaction_type][status_code];
} else if (transaction_type === 'withdrawal' && isWithdrawal(status_code)) {
    return data[transaction_type][status_code];
}
```

2023-03-15 05:55 UTC, hamid-deriv commented on packages/cashier/src/types/transactions.types.ts
> +export type TStatusCode =
Add a blank line before this to have better readability.

2023-03-15 08:22 UTC, farzin-deriv commented on packages/cashier/src/constants/transaction-status.tsx
> +    return transaction_status as { name: string; description: ReactNode; renderer: string; transaction_hash: string };
```suggestion
    if (transaction_type === 'deposit' && isDeposit(status_code)) {
        return transaction_status = status_list[transaction_type][status_code];
    } else if (transaction_type === 'withdrawal' && isWithdrawal(status_code)) {
        return transaction_status = status_list[transaction_type][status_code];
    }
```

2023-03-15 14:27 UTC, rostislav-deriv commented on packages/cashier/src/constants/transaction-status.tsx
> +        Object.keys(status_list.withdrawal).includes(status);
The previous type guards (`... => typeof key === typeof data.deposit;`) weren't working because `typeof key` was `string`, so I made these, hope they're ok

2023-03-16 03:14 UTC, hamid-deriv commented on packages/cashier/src/components/recent-transaction/__tests__/recent-transaction.spec.tsx
> +    let history: BrowserHistory, mockRootStore: TRootStore;
The type of the `mockRootStore` should be `TStores` from `@deriv/store`.

```suggestion
    let history: BrowserHistory, mockRootStore: TStores;
```

2023-03-16 04:02 UTC, farzin-deriv commented on packages/cashier/src/constants/transaction-status.tsx
> +    return transaction_status as { name: string; description: ReactNode; renderer: string; transaction_hash: string };
@rostislav-deriv I still don't understand why you need to cast, We can just return instead of keeping the value in a `any` variable and then having to cast the type 🤔 

https://github.com/rostislav-deriv/deriv-app/pull/3#discussion_r1136683484

2023-03-16 08:03 UTC, rostislav-deriv commented on packages/cashier/src/constants/transaction-status.tsx
> +    return transaction_status as { name: string; description: ReactNode; renderer: string; transaction_hash: string };
If we do like in the first pic, there's an ESLint error @farzin-deriv, hence the extra variable
Should I suppress the error?

![Screenshot 2023-03-16 at 11 00 25](https://user-images.githubusercontent.com/119863957/225552416-f1890d3f-c032-4053-97b8-ff085b672650.png)
![Screenshot 2023-03-16 at 11 00 54](https://user-images.githubusercontent.com/119863957/225552446-2f8452fc-b606-43fc-8a14-cbce5d177459.png)

2023-03-16 08:06 UTC, farzin-deriv commented on packages/cashier/src/constants/transaction-status.tsx
> +    return transaction_status as { name: string; description: ReactNode; renderer: string; transaction_hash: string };
@rostislav-deriv No your function needs a default return, Because both returns are in an if condition ESLint assume that they might never happen so you need to have a default return at the end of the function, Can be null or a default value from `status_list`.

When you use `as` this is still happening but we are ignoring the error and not handling the default case 😬

2023-03-16 08:58 UTC, farzin-deriv approved these changes

2023-03-16 09:34 UTC, hamid-deriv approved these changes

2023-03-16 10:09 UTC, merged