Rostislav / 84830 / TS migration of payment agent UI component and store
rostislav-deriv/deriv-app pull request #6
Opened 2023-04-07 10:24 UTC by rostislav-deriv

## Changes:

Please include a summary of the change and which issue is fixed below:
-   ...

## When you need to add unit test

-   [ ] If this change disrupt current flow
-   [ ] If this change is adding new flow

## When you need to add integration test

-   [ ] If components from external libraries are being used to define the flow, e.g. @deriv/components
-   [ ] If it relies on a very specific set of props with no default behavior for the current component.

## Test coverage checklist (for reviewer)

-   [ ] Ensure utility / function has a test case 
-   [ ] Ensure all the tests are passing

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2023-04-07 13:52 UTC, rostislav-deriv commented on packages/cashier/src/stores/__tests__/payment-agent-store.spec.tsx
> +                    paymentagent_list: JSON.parse(JSON.stringify(mocked_payment_agent_list)),
Correct me if I'm wrong but we need to make a copy of the object here, since we change the values by link in test cases

2023-04-07 13:57 UTC, rostislav-deriv commented on packages/cashier/src/types/payment-agent.types.ts
I used the names for the types from [here](https://github.com/binary-com/deriv-app/pull/6425/files#diff-37325a9a38397b1f0eafe6da1d9d36c6513004ab46b6e5cafb0a7ec05891431f)

2023-04-10 12:34 UTC, heorhi-deriv commented on packages/cashier/src/stores/payment-agent-store.ts
> -                                supported_bank.payment_method,
@rostislav-deriv we should leave `getNormalizedPaymentMethod` here.

2023-04-10 13:19 UTC, rostislav-deriv commented on packages/cashier/src/stores/payment-agent-store.ts
> -                                supported_bank.payment_method,
Returned it

2023-04-10 13:28 UTC, rostislav-deriv commented on packages/cashier/src/pages/payment-agent/payment-agent-withdrawal-locked/payment-agent-withdrawal-locked.tsx
> +import { TServerError } from 'Types';
Yes, changed to relative import

2023-04-11 23:58 UTC, rostislav-deriv commented on packages/cashier/src/pages/payment-agent/__tests__/payment-agent.spec.tsx
> +    let mockRootStore: TStores;
Setting this type and not `TRootStore` because of [this](https://github.com/binary-com/deriv-app/pull/7896/files#diff-657f422ad1ee97d480ed3a82ffc140d2c54b08a9f0062c20896439ba710a618cL4-R4)

2023-04-12 14:08 UTC, heorhi-deriv approved these changes

2023-04-13 02:52 UTC, farzin-deriv requested changes
@rostislav-deriv Please update your branch with the master as https://github.com/binary-com/deriv-app/pull/7896 was merged 🙏🏻

2023-04-13 09:37 UTC, farzin-deriv reviewed
@rostislav-deriv It seems like the code from #7 exists in this PR too but the changes after review is not here 😕

2023-04-13 09:37 UTC, farzin-deriv commented on packages/cashier/src/pages/payment-agent/payment-agent-withdraw-confirm/payment-agent-withdraw-confirm.tsx
> +    verification_code: string;
@rostislav-deriv Can you check the component usage and see if we can just get it from client store instead of prop 🙏🏻 🤔

2023-04-13 09:37 UTC, farzin-deriv commented on packages/cashier/src/pages/payment-agent/payment-agent-card/payment-agent-card.tsx
>      const message = {
@rostislav-deriv There is a type error on line 33.

2023-04-13 09:37 UTC, farzin-deriv commented on packages/cashier/src/pages/payment-agent/payment-agent-card/payment-agent-card.tsx
> +const PaymentAgentCard = ({ is_dark_mode_on, is_deposit, payment_agent }: TPaymentAgentCard) => {
@rostislav-deriv Should we give boolean props a default value of false 🤔

2023-04-13 09:37 UTC, farzin-deriv commented on packages/cashier/src/components/empty-state/empty-state.tsx
> +    title?: string | React.ReactNode;
@rostislav-deriv `string` is already included in `React.ReactNode` 👀

2023-04-13 09:37 UTC, farzin-deriv commented on packages/cashier/src/components/crypto-fiat-converter/crypto-fiat-converter.tsx
> +    hint?: string | React.ReactNode;
@rostislav-deriv Same here 👀

2023-04-13 09:57 UTC, rostislav-deriv commented on packages/cashier/src/pages/payment-agent/payment-agent.tsx
> +    setSideNotes: VoidFunction;
Can't believe I wrote this, even the name implies it's not a `VoidFunction`

2023-04-13 10:17 UTC, rostislav-deriv commented on packages/cashier/src/pages/payment-agent/payment-agent-card/payment-agent-card.tsx
>      const message = {
Yes, I mentioned it [here](https://github.com/rostislav-deriv/deriv-app/pull/6#discussion_r1160704398), not sure how to fix it as of now 😓

2023-04-14 08:05 UTC, rostislav-deriv commented
> @rostislav-deriv It seems like the code from #7 exists in this PR too but the changes after review is not here 😕

@farzin-deriv I believe the changes from these 3 commits made after your first review are in this PR as well, except `TTarget` is not removed as in #7 because it's actually used, as are the `TExtendedPaymentAgentList` & `TExtendedPaymentAgentFields` types

2023-04-14 08:43 UTC, farzin-deriv approved these changes

2023-04-14 08:43 UTC, farzin-deriv commented on packages/cashier/src/pages/payment-agent/payment-agent-withdraw-confirm/payment-agent-withdraw-confirm.tsx
> +    const verification_code = client.verification_code.payment_agent_withdraw;
```suggestion
    const { loginid: client_loginid, verification_code } = client;
    const { payment_agent } = useCashierStore();
```

2023-04-14 08:43 UTC, farzin-deriv commented on packages/cashier/src/pages/payment-agent/payment-agent-card/payment-agent-card.tsx
>      const message = {
@rostislav-deriv Oh I missed that comment, Sorry man 🌹 

Seems like the type in the `ExpansionPanel` is wrong, We can ignore the error in this PR and fix it later 🙇🏻

2023-04-14 08:58 UTC, rostislav-deriv commented on packages/cashier/src/pages/payment-agent/payment-agent-card/payment-agent-card.tsx
>      const message = {
@heorhi-deriv helped with fixing it in terms of _using_ `ExpansionPanel`, but inside the `ExpansionPanel` itself there are a lot of problems with the typing for rendering nested arrays; it would require a lot of refactoring to align the types with the actual logic

2023-04-14 09:41 UTC, merged